name: Deploy tema

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: FTP
    steps:
      - uses: actions/checkout@v4

      - name: Inspecionar estrutura
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type d -name "agenciaaids" || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Minificar app.js
        run: |
          npm install -g terser
          terser assets/js/app.js -o assets/js/app.min.js -c -m

      - name: Minificar CSS components com Lightning CSS
        run: |
          npm install -g lightningcss-cli
          for file in assets/css/components/*.css; do
            lightningcss --minify --nesting --targets '>= 0.25%' "$file" -o "$file"
          done

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /wp-content/themes/agenciaaids/
          timeout: 600000
          log-level: verbose
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/.vscode/**
            **/*.map
            **/README.md
            **/tasks.txt
